(function(){
  const supabase=window.gateSupabase;if(!supabase)return;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let currentProfile=null;

  // Create a Staff navigation tab and view without changing index.html.
  const tabs=document.getElementById('tabs');
  const staffTab=document.createElement('button');staffTab.dataset.view='staff';staffTab.className='staff-nav';staffTab.textContent='Staff';tabs?.appendChild(staffTab);
  const main=document.querySelector('main');
  const staffView=document.createElement('section');staffView.className='view';staffView.id='staff';staffView.innerHTML='<div class="section-title"><h2>Staff Tools</h2><span class="see-all" id="staffRoleLabel"></span></div><div id="staffContent"></div>';main?.appendChild(staffView);
  staffTab.addEventListener('click',()=>window.switchView?.('staff'));

  async function loadAnnouncement(){
    const {data,error}=await supabase.from('announcements').select('author_name,body,created_at').eq('is_pinned',true).order('created_at',{ascending:false}).limit(1).maybeSingle();
    if(error||!data)return;
    const note=document.querySelector('.pin-note');if(!note)return;
    const date=new Date(data.created_at).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
    note.innerHTML=`<div class="pin"></div><span class="who">${esc(data.author_name)}</span>${esc(data.body).replace(/\n/g,'<br>')}<span class="when">${esc(date)}</span>`;
  }

  async function createPoll(e){e.preventDefault();const form=e.currentTarget,status=form.querySelector('.staff-status');const q=form.question.value.trim();const options=[...form.querySelectorAll('[name="option"]')].map(x=>x.value.trim()).filter(Boolean);if(!q||options.length<2){status.textContent='Enter a question and at least 2 choices.';return}status.textContent='Creating…';const {data:poll,error}=await supabase.from('polls').insert({question:q,is_open:true}).select('id').single();if(error){status.textContent=error.message;return}const rows=options.map((label,i)=>({poll_id:poll.id,label,sort_order:i+1}));const {error:optError}=await supabase.from('poll_options').insert(rows);if(optError){status.textContent=optError.message;return}form.reset();status.textContent='Poll created.';await loadPollManager();setTimeout(()=>status.textContent='',1600)}

  async function loadPollManager(){const host=document.getElementById('staffPollList');if(!host)return;const {data,error}=await supabase.from('polls').select('id,question,is_open,created_at,poll_options(id,label),poll_votes(id)').order('created_at',{ascending:false});if(error){host.innerHTML=`<div class="staff-empty">${esc(error.message)}</div>`;return}host.innerHTML=(data||[]).map(p=>`<div class="staff-item"><div class="staff-item-top"><div><h4>${esc(p.question)}</h4><div class="staff-meta">${p.poll_votes?.length||0} votes · ${p.poll_options?.length||0} choices</div></div><span class="staff-badge ${p.is_open?'live':''}">${p.is_open?'OPEN':'CLOSED'}</span></div><div class="staff-toolbar"><button class="btn btn-ghost" data-action="toggle-poll" data-id="${p.id}" data-open="${p.is_open}">${p.is_open?'Close Poll':'Reopen Poll'}</button><button class="btn btn-ghost staff-danger" data-action="delete-poll" data-id="${p.id}">Delete</button></div></div>`).join('')||'<div class="staff-empty">No polls yet.</div>'}

  async function postAnnouncement(e){e.preventDefault();const form=e.currentTarget,status=form.querySelector('.staff-status'),body=form.body.value.trim();if(!body){status.textContent='Write an announcement first.';return}status.textContent='Posting…';await supabase.from('announcements').update({is_pinned:false}).eq('is_pinned',true);const {error}=await supabase.from('announcements').insert({author_id:window.gateAuthState?.session?.user?.id,author_name:currentProfile?.display_name||'League Staff',body,is_pinned:true});if(error){status.textContent=error.message;return}form.reset();status.textContent='Announcement posted.';await Promise.all([loadAnnouncement(),loadAnnouncements()]);setTimeout(()=>status.textContent='',1600)}

  async function loadAnnouncements(){const host=document.getElementById('staffAnnouncementList');if(!host)return;const {data,error}=await supabase.from('announcements').select('*').order('created_at',{ascending:false}).limit(10);if(error){host.innerHTML=`<div class="staff-empty">${esc(error.message)}</div>`;return}host.innerHTML=(data||[]).map(a=>`<div class="staff-item"><div class="staff-item-top"><div><h4>${esc(a.author_name)}</h4><div class="staff-meta">${new Date(a.created_at).toLocaleString()}</div></div>${a.is_pinned?'<span class="staff-badge live">PINNED</span>':''}</div><div style="margin-top:8px;color:var(--muted);font-size:12px">${esc(a.body)}</div><div class="staff-toolbar"><button class="btn btn-ghost staff-danger" data-action="delete-announcement" data-id="${a.id}">Delete</button></div></div>`).join('')||'<div class="staff-empty">No announcements yet.</div>'}

  async function loadModeration(){const host=document.getElementById('staffBoardList');if(!host)return;const {data,error}=await supabase.from('board_posts').select('id,author,title,category,created_at').order('created_at',{ascending:false}).limit(12);if(error){host.innerHTML=`<div class="staff-empty">${esc(error.message)}</div>`;return}host.innerHTML=(data||[]).map(p=>`<div class="staff-item"><div class="staff-item-top"><div><h4>${esc(p.title)}</h4><div class="staff-meta">${esc(p.author)} · ${esc(p.category)} · ${new Date(p.created_at).toLocaleString()}</div></div></div><div class="staff-toolbar"><button class="btn btn-ghost staff-danger" data-action="delete-post" data-id="${p.id}">Delete Post</button></div></div>`).join('')||'<div class="staff-empty">No board posts.</div>'}

  async function loadProfiles(){const box=document.getElementById('siteAdminProfiles');if(!box||currentProfile?.role!=='site_admin')return;const {data,error}=await supabase.from('profiles').select('id,display_name,role,created_at').order('created_at');if(error){box.innerHTML=`<div class="staff-empty">${esc(error.message)}</div>`;return}box.innerHTML=(data||[]).map(p=>`<div class="staff-item"><div class="staff-item-top"><div><h4>${esc(p.display_name||'Unnamed User')}</h4><div class="staff-meta">${esc(p.role)}</div></div><select data-role-user="${p.id}"><option value="member" ${p.role==='member'?'selected':''}>Member</option><option value="commissioner" ${p.role==='commissioner'?'selected':''}>Commissioner</option><option value="site_admin" ${p.role==='site_admin'?'selected':''}>Site Admin</option></select></div></div>`).join('')}

  function renderDashboard(){const host=document.getElementById('staffContent');if(!host)return;const siteAdmin=currentProfile?.role==='site_admin';document.getElementById('staffRoleLabel').textContent=siteAdmin?'SITE ADMIN':'COMMISSIONER';host.innerHTML=`<div class="staff-role-note"><strong>${siteAdmin?'Site Admin':'Commissioner'} access:</strong> ${siteAdmin?'full league-site staff controls plus account-role management.':'polls, commissioner announcements, and message-board moderation.'}</div><div class="staff-grid"><div class="panel staff-panel"><h3>Create Poll</h3><form class="staff-form" id="staffPollForm"><input name="question" maxlength="200" placeholder="Poll question" required><div class="staff-options"><input name="option" maxlength="120" placeholder="Choice 1" required><input name="option" maxlength="120" placeholder="Choice 2" required><input name="option" maxlength="120" placeholder="Choice 3 (optional)"><input name="option" maxlength="120" placeholder="Choice 4 (optional)"></div><div class="staff-actions"><span class="staff-status"></span><button class="btn btn-primary">Create Poll</button></div></form></div><div class="panel staff-panel"><h3>Commissioner Announcement</h3><form class="staff-form" id="staffAnnouncementForm"><textarea name="body" maxlength="1200" placeholder="Post an announcement to the homepage…" required></textarea><div class="staff-actions"><span class="staff-status"></span><button class="btn btn-primary">Publish</button></div></form></div><div class="panel staff-panel"><h3>Manage Polls</h3><div class="staff-list" id="staffPollList"></div></div><div class="panel staff-panel"><h3>Message Board Moderation</h3><div class="staff-list" id="staffBoardList"></div></div><div class="panel staff-panel"><h3>Recent Announcements</h3><div class="staff-list" id="staffAnnouncementList"></div></div>${siteAdmin?'<div class="panel staff-panel"><h3>User Roles</h3><div class="staff-role-note">Only the site admin can change staff roles.</div><div class="staff-list" id="siteAdminProfiles"></div></div>':''}</div>`;document.getElementById('staffPollForm').addEventListener('submit',createPoll);document.getElementById('staffAnnouncementForm').addEventListener('submit',postAnnouncement);host.addEventListener('click',handleAction);host.addEventListener('change',handleRoleChange);Promise.all([loadPollManager(),loadModeration(),loadAnnouncements(),loadProfiles()])}

  async function handleAction(e){const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,id=b.dataset.id;b.disabled=true;if(action==='toggle-poll'){await supabase.from('polls').update({is_open:b.dataset.open!=='true'}).eq('id',id);await loadPollManager()}if(action==='delete-poll'&&confirm('Delete this poll and all of its votes?')){await supabase.from('polls').delete().eq('id',id);await loadPollManager()}if(action==='delete-post'&&confirm('Delete this message-board post and its replies?')){await supabase.from('board_posts').delete().eq('id',id);await loadModeration()}if(action==='delete-announcement'&&confirm('Delete this announcement?')){await supabase.from('announcements').delete().eq('id',id);await Promise.all([loadAnnouncements(),loadAnnouncement()])}b.disabled=false}

  async function handleRoleChange(e){const select=e.target.closest('[data-role-user]');if(!select||currentProfile?.role!=='site_admin')return;select.disabled=true;const {error}=await supabase.from('profiles').update({role:select.value}).eq('id',select.dataset.roleUser);if(error)alert(error.message);select.disabled=false}

  window.addEventListener('gate-auth-changed',e=>{currentProfile=e.detail.profile;const staff=currentProfile&&['site_admin','commissioner'].includes(currentProfile.role);staffTab.classList.toggle('visible',!!staff);if(!staff&&document.getElementById('staff')?.classList.contains('active'))window.switchView?.('home');if(staff)renderDashboard()});
  loadAnnouncement();
  supabase.channel('1048-announcements').on('postgres_changes',{event:'*',schema:'public',table:'announcements'},()=>{loadAnnouncement();if(currentProfile)loadAnnouncements()}).subscribe();
})();
