const tabButtons=document.querySelectorAll('#tabs button');
function switchView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(name)?.classList.add('active');tabButtons.forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'})}
window.switchView=switchView;tabButtons.forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.view)));
document.querySelectorAll('.filter-pills .pill').forEach(p=>p.addEventListener('click',()=>{document.querySelectorAll('.filter-pills .pill').forEach(x=>x.classList.remove('active'));p.classList.add('active')}));
document.querySelectorAll('.accordion-item').forEach(item=>item.querySelector('.accordion-head')?.addEventListener('click',()=>item.classList.toggle('open')));

/* EDIT MEMBER DATA HERE
Each season: [year, finalFinish, "teamName", "wins-losses", pointsFor, pointsAgainst]
Use null for unavailable point totals. */
const leagueMembers=[
{number:'01',name:'George Travis',role:'Commissioner',seasons:[[2017,2,'Free Zeke','8-5',null,null],[2018,2,'Beasts of the East','10-3',null,null],[2019,8,'Quon Solo and The Ewoks','7-6',1547.10,1404.70],[2020,6,"Tongy's Banned 4 Semester",'9-4',1640.76,1522.54],[2021,6,'Beasts of the East','9-5',1784.84,1515.50],[2022,1,'A, B, Ceedee, **** You','8-6',1670.50,1491.60],[2023,4,'Tony 2 Step','7-7',1613.64,1700.54],[2024,2,'Justified ✨','7-7',1733.48,1710.04],[2025,5,'Shiesty Szn','8-6',1686.08,1565.66]]},
{number:'02',name:'Jared Hall',role:'League Member',seasons:[[2017,1,'Flash In The Flex','10-3',null,null],[2018,3,'Is This Your Champ?','10-3',null,null],[2019,4,'No Kaep','9-4',1670.78,1419.84],[2020,5,'No Kap','7-6',1680.34,1610.02],[2021,3,'Bishop Sycamore','7-7',1913.62,1763.16],[2022,5,'Herbie Fully Goated','7-7',1648.70,1717.78],[2023,1,'Crown The King 👑','9-5',1815.90,1665.62],[2024,1,'The Diddlers','11-3',1868.66,1686.26],[2025,11,'Darty at 1048','7-7',1565.22,1602.38]]},
{number:'03',name:'Kyle Fowler',role:'League Member',seasons:[]},{number:'04',name:'Bryan Hunt',role:'League Member',seasons:[]},{number:'05',name:'Brian Heino',role:'League Member',seasons:[]},{number:'06',name:'Vincent Cannarozzi',role:'League Member',seasons:[]},{number:'07',name:'James Brochu',role:'League Member',seasons:[]},{number:'08',name:'JD Daley',role:'League Member',seasons:[]},{number:'09',name:'Thomas Speer',role:'League Member',seasons:[]},{number:'10',name:'Collin Krum',role:'League Member',seasons:[]},{number:'11',name:'German Haro',role:'League Member',seasons:[]},{number:'12',name:'Trevor Hash',role:'League Member',seasons:[]}
];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function totals(m){let wins=0,losses=0,pf=0,pa=0,pfs=0;const finishes=[];m.seasons.forEach(s=>{const r=String(s[3]||'').match(/\d+/g)||[];wins+=Number(r[0]||0);losses+=Number(r[1]||0);if(Number.isFinite(s[4])){pf+=s[4];pfs++}if(Number.isFinite(s[5]))pa+=s[5];if(Number.isFinite(Number(s[1])))finishes.push(Number(s[1]))});return{wins,losses,pf,pa,pfs,pct:wins+losses?wins/(wins+losses):0,avg:finishes.length?finishes.reduce((a,b)=>a+b,0)/finishes.length:null,best:finishes.length?Math.min(...finishes):null,titles:finishes.filter(x=>x===1).length}}
const num=(v,d=1)=>Number.isFinite(v)?v.toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
function renderMembers(){const grid=document.getElementById('membersGrid');if(!grid)return;grid.innerHTML=leagueMembers.map((m,i)=>{const t=totals(m),has=m.seasons.length;return `<article class="member-card" data-i="${i}" tabindex="0"><div class="member-head"><div class="locker-num">${esc(m.number)}</div><div><div class="team">${esc(m.name)}</div><div class="mgr">${esc(m.role)}</div></div></div>${has?`<div class="member-stats"><div class="member-stat"><span class="label">Record</span><span class="value accent">${t.wins}-${t.losses}</span></div><div class="member-stat"><span class="label">Win %</span><span class="value">${(t.pct*100).toFixed(1)}%</span></div><div class="member-stat"><span class="label">Titles</span><span class="value">${t.titles}</span></div></div>`:'<div class="member-empty">Career data ready to be added.</div>'}</article>`}).join('');grid.querySelectorAll('.member-card').forEach(card=>{const open=()=>openMember(Number(card.dataset.i));card.addEventListener('click',open);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}})})}
function openMember(i){const m=leagueMembers[i],t=totals(m);document.getElementById('memberModalName').textContent=m.name;document.getElementById('memberModalRole').textContent=`${m.role} • ${m.seasons.length} seasons recorded`;const boxes=[['Career Record',`${t.wins}-${t.losses}`],['Win Rate',`${(t.pct*100).toFixed(1)}%`],['Championships',t.titles],['Average Finish',num(t.avg)],['Best Finish',t.best?`#${t.best}`:'—'],['Career PF',t.pfs?num(t.pf):'—']];document.getElementById('careerSummary').innerHTML=boxes.map(x=>`<div class="career-box"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join('');document.getElementById('seasonRows').innerHTML=m.seasons.length?[...m.seasons].sort((a,b)=>b[0]-a[0]).map(s=>{const diff=Number.isFinite(s[4])&&Number.isFinite(s[5])?s[4]-s[5]:null;return `<tr><td>${s[0]}</td><td class="${Number(s[1])===1?'finish-champ':''}">${Number(s[1])===1?'🏆 ':''}#${s[1]}</td><td>${esc(s[2])}</td><td>${esc(s[3])}</td><td>${num(s[4])}</td><td>${num(s[5])}</td><td>${diff===null?'—':`${diff>=0?'+':''}${num(diff)}`}</td></tr>`}).join(''):'<tr><td colspan="7" class="member-empty">No season data has been entered yet.</td></tr>';document.getElementById('memberModal').classList.add('open')}
function closeMember(){document.getElementById('memberModal')?.classList.remove('open')}
document.getElementById('memberModalClose')?.addEventListener('click',closeMember);document.getElementById('memberModal')?.addEventListener('click',e=>{if(e.target.id==='memberModal')closeMember()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMember()});renderMembers();
