(function(){
  const history=document.getElementById('history');
  if(!history||history.dataset.historyLayout==='ready')return;
  history.dataset.historyLayout='ready';
  if(!document.querySelector('link[href="css/history.css"]')){const css=document.createElement('link');css.rel='stylesheet';css.href='css/history.css';document.head.appendChild(css)}
  const title=history.querySelector('.section-title'),timeline=history.querySelector('.timeline'),recordGrid=history.querySelector('.record-grid'),shame=history.querySelector('.shame');
  if(!timeline||!recordGrid||!shame)return;
  const championsPanel=timeline.closest('.panel')||timeline.parentElement,recordsPanel=recordGrid.closest('.panel')||recordGrid.parentElement,shamePanel=shame.closest('.panel')||shame.parentElement;
  const shell=document.createElement('div');shell.className='history-shell';shell.innerHTML=`<div class="history-intro"><div><span class="history-eyebrow">1048 ARCHIVES</span><h3>Ten seasons of league lore</h3><p>Browse champions, full season standings, all-time records, and the moments nobody is allowed to forget.</p></div></div><div class="history-subnav" role="tablist" aria-label="League history sections"><button class="active" type="button" data-history-tab="champions">🏆 Champions</button><button type="button" data-history-tab="seasons">📅 Seasons</button><button type="button" data-history-tab="records">📖 Record Book</button><button type="button" data-history-tab="shame">💩 Wall of Shame</button></div><div class="history-tab-panels"><section class="history-tab-panel active" data-history-panel="champions"></section><section class="history-tab-panel" data-history-panel="seasons"></section><section class="history-tab-panel" data-history-panel="records"></section><section class="history-tab-panel" data-history-panel="shame"></section></div>`;
  if(title)title.insertAdjacentElement('afterend',shell);else history.prepend(shell);
  const champHost=shell.querySelector('[data-history-panel="champions"]'),seasonHost=shell.querySelector('[data-history-panel="seasons"]'),recordHost=shell.querySelector('[data-history-panel="records"]'),shameHost=shell.querySelector('[data-history-panel="shame"]');
  championsPanel.classList.add('history-content-panel');recordsPanel.classList.add('history-content-panel');shamePanel.classList.add('history-content-panel');champHost.appendChild(championsPanel);recordHost.appendChild(recordsPanel);shameHost.appendChild(shamePanel);
  const cleanHeading=(panel,label,sub)=>{const old=panel.querySelector(':scope > h3');if(old)old.remove();const head=document.createElement('div');head.className='history-section-head';head.innerHTML=`<div><span>${label}</span><h3>${sub}</h3></div>`;panel.prepend(head)};
  cleanHeading(championsPanel,'CHAMPIONSHIP ARCHIVE','Champions Through the Years');cleanHeading(recordsPanel,'LEAGUE RECORD BOOK','Records & Milestones');cleanHeading(shamePanel,'HALL OF MISFORTUNE','Wall of Shame');
  function activate(name){shell.querySelectorAll('[data-history-tab]').forEach(b=>b.classList.toggle('active',b.dataset.historyTab===name));shell.querySelectorAll('[data-history-panel]').forEach(p=>p.classList.toggle('active',p.dataset.historyPanel===name))}
  shell.querySelectorAll('[data-history-tab]').forEach(btn=>btn.addEventListener('click',()=>activate(btn.dataset.historyTab)));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=v=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:2}):'—';
  async function loadSeasonArchive(){
    seasonHost.innerHTML='<div class="panel history-content-panel"><div class="history-loading">Loading season archive…</div></div>';
    try{
      const response=await fetch('data/seasons.json',{cache:'no-store'});if(!response.ok)throw new Error(`seasons.json returned HTTP ${response.status}`);const payload=await response.json();const seasons=Array.isArray(payload.seasons)?payload.seasons:[];if(!seasons.length)throw new Error('No seasons found');
      seasonHost.innerHTML='<div class="panel history-content-panel season-archive-panel"><div class="history-section-head"><div><span>SEASON ARCHIVE</span><h3>Year-by-Year Standings</h3></div></div><div class="season-year-nav"></div><div class="season-detail"></div></div>';
      const nav=seasonHost.querySelector('.season-year-nav'),detail=seasonHost.querySelector('.season-detail'),sorted=[...seasons].sort((a,b)=>b.year-a.year);
      nav.innerHTML=sorted.map((s,i)=>`<button type="button" class="${i===0?'active':''}" data-season-year="${s.year}">${s.year}</button>`).join('');
      function renderSeason(year){const season=sorted.find(s=>Number(s.year)===Number(year));if(!season)return;nav.querySelectorAll('button').forEach(btn=>btn.classList.toggle('active',Number(btn.dataset.seasonYear)===Number(year)));const champ=season.champion||{};detail.innerHTML=`<div class="season-summary"><div><span class="season-label">${esc(season.leagueName)}</span><h4>${season.year} Season</h4></div><div class="season-champion"><span>🏆 Champion</span><strong>${esc(champ.ownerName||'—')}</strong><small>${esc(champ.teamName||'')}</small></div></div><div class="season-table-wrap"><table class="season-archive-table"><thead><tr><th>Finish</th><th>Team</th><th>Owner</th><th>Record</th><th>PF</th><th>PA</th><th>Diff</th><th>RS</th></tr></thead><tbody>${(season.standings||[]).map(team=>`<tr class="${Number(team.finalFinish)===1?'season-champ-row':''}"><td class="season-finish">${Number(team.finalFinish)===1?'🏆 ':''}#${esc(team.finalFinish)}</td><td><strong>${esc(team.teamName)}</strong></td><td>${esc(team.ownerName)}</td><td>${esc(team.record)}</td><td>${num(team.pointsFor)}</td><td>${num(team.pointsAgainst)}</td><td class="${Number(team.pointDiff)>=0?'positive-diff':'negative-diff'}">${Number(team.pointDiff)>=0?'+':''}${num(team.pointDiff)}</td><td>#${esc(team.regularSeasonStanding)}</td></tr>`).join('')}</tbody></table></div>`}
      nav.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>renderSeason(btn.dataset.seasonYear)));renderSeason(sorted[0].year);
    }catch(error){console.error('Unable to load season archive:',error);seasonHost.innerHTML='<div class="panel history-content-panel"><div class="history-loading">Season archive could not be loaded.</div></div>'}
  }
  loadSeasonArchive();
  const observer=new MutationObserver(()=>{const shameTimeline=document.getElementById('shameTimeline');if(shameTimeline&&shameTimeline.parentElement!==shamePanel)shamePanel.appendChild(shameTimeline)});observer.observe(history,{childList:true,subtree:true});
})();