(function(){
  const supabase=window.gateSupabase;if(!supabase)return;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let currentProfile=null,activeTab='members',cache={members:[],champions:[],records:[],shame:[]};

  const parseRecord=r=>{const p=String(r||'').split('-').map(Number);return{w:p[0]||0,l:p[1]||0,t:p[2]||0}};
  const recordText=(w,l,t)=>t?`${w}-${l}-${t}`:`${w}-${l}`;
  function memberTotals(m){let w=0,l=0,t=0;const finishes=[];(m.member_seasons||[]).forEach(s=>{const r=parseRecord(s.record);w+=r.w;l+=r.l;t+=r.t;finishes.push(Number(s.final_finish))});const g=w+l+t;return{w,l,t,pct:g?(w+t*.5)/g:0,titles:finishes.filter(x=>x===1).length,avg:finishes.length?finishes.reduce((a,b)=>a+b,0)/finishes.length:null}}
  function toast(msg,type='ok'){let t=document.getElementById('contentToast');if(!t){t=document.createElement('div');t.id='contentToast';t.className='content-toast';document.body.appendChild(t)}t.className=`content-toast show ${type}`;t.textContent=msg;clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)}

  function ensureModal(){if(document.getElementById('contentModal'))return;const m=document.createElement('div');m.id='contentModal';m.className='content-modal';m.innerHTML='<div class="content-modal-card"><div class="content-modal-head"><div><h2 id="contentModalTitle">Edit</h2><div class="staff-meta" id="contentModalSub"></div></div><button class="modal-close" data-modal-close>×</button></div><form id="contentModalForm" class="content-form"></form></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('[data-modal-close]'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()})}
  function openModal(title,sub,html,onSubmit){ensureModal();const m=document.getElementById('contentModal'),f=document.getElementById('contentModalForm');document.getElementById('contentModalTitle').textContent=title;document.getElementById('contentModalSub').textContent=sub||'';f.innerHTML=html;f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('[type=submit]');if(btn)btn.disabled=true;try{await onSubmit(new FormData(f));closeModal();await refreshAll();toast('Saved ✓')}catch(err){toast(err.message||String(err),'error')}finally{if(btn)btn.disabled=false}};m.classList.add('open')}
  function closeModal(){document.getElementById('contentModal')?.classList.remove('open')}
  const field=(label,name,value='',type='text',extra='')=>`<label class="content-field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
  const textarea=(label,name,value='',extra='')=>`<label class="content-field content-field-wide"><span>${label}</span><textarea name="${name}" ${extra}>${esc(value)}</textarea></label>`;
  const actions=()=>'<div class="content-form-actions"><button type="button" class="btn btn-ghost" data-modal-close>Cancel</button><button type="submit" class="btn btn-primary">Save Changes</button></div>';

  async function importCurrentSiteData(btn){btn.disabled=true;btn.textContent='Importing…';try{if(typeof leagueMembers==='undefined')throw new Error('Current member data was not found.');const memberRows=leagueMembers.map((m,i)=>({member_number:m.number,name:m.name,role_label:m.role,sort_order:i+1}));let r=await supabase.from('league_members').upsert(memberRows,{onConflict:'member_number'});if(r.error)throw r.error;const {data:dbMembers,error}=await supabase.from('league_members').select('id,member_number');if(error)throw error;const map=Object.fromEntries(dbMembers.map(m=>[m.member_number,m.id]));const seasons=[];leagueMembers.forEach(m=>(m.seasons||[]).forEach(s=>seasons.push({member_id:map[m.number],season_year:s[0],final_finish:s[1],team_name:s[2],record:s[3],points_for:s[4],points_against:s[5]})));r=await supabase.from('member_seasons').upsert(seasons,{onConflict:'member_id,season_year'});if(r.error)throw r.error;toast('Import complete ✓');await refreshAll()}catch(e){toast(e.message||String(e),'error')}finally{btn.disabled=false;btn.textContent='Import Current Site Data'}}

  async function loadData(){const [m,c,r,s]=await Promise.all([
    supabase.from('league_members').select('id,member_number,name,role_label,sort_order,member_seasons(id,season_year,final_finish,team_name,record,points_for,points_against)').order('sort_order'),
    supabase.from('league_champions').select('*').order('season_year',{ascending:false}),
    supabase.from('league_records').select('*').order('sort_order'),
    supabase.from('wall_of_shame').select('*').order('season_year',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false})
  ]);for(const x of [m,c,r,s])if(x.error)throw x.error;cache={members:m.data||[],champions:c.data||[],records:r.data||[],shame:s.data||[]}}

  function renderManager(){const host=document.getElementById('leagueContentManager');if(!host)return;host.innerHTML=`<div class="content-tabs"><button class="${activeTab==='members'?'active':''}" data-content-tab="members">Members</button><button class="${activeTab==='history'?'active':''}" data-content-tab="history">League History</button><button class="${activeTab==='records'?'active':''}" data-content-tab="records">Record Book</button><button class="${activeTab==='shame'?'active':''}" data-content-tab="shame">Wall of Shame</button></div><div id="contentTabBody"></div>`;renderTab()}
  function renderTab(){const body=document.getElementById('contentTabBody');if(!body)return;if(activeTab==='members')renderMembers(body);if(activeTab==='history')renderChampions(body);if(activeTab==='records')renderRecords(body);if(activeTab==='shame')renderShame(body)}

  function renderMembers(body){body.innerHTML=`<div class="content-toolbar"><div><h3>League Members</h3><div class="staff-meta">Manage owners and add each season without touching code.</div></div><button class="btn btn-primary" data-content-action="add-member">+ Add Member</button></div><div class="content-member-grid">${cache.members.map(m=>{const t=memberTotals(m),seasons=[...(m.member_seasons||[])].sort((a,b)=>b.season_year-a.season_year);return `<article class="content-member-card"><div class="content-member-head"><div class="locker-num">${esc(m.member_number)}</div><div><h3>${esc(m.name)}</h3><div class="staff-meta">${esc(m.role_label)} · ${seasons.length} seasons</div></div></div><div class="content-career"><span><b>${recordText(t.w,t.l,t.t)}</b> Career</span><span><b>${(t.pct*100).toFixed(1)}%</b> Win</span><span><b>${t.titles}</b> Titles</span><span><b>${t.avg===null?'—':t.avg.toFixed(1)}</b> Avg Finish</span></div><div class="content-member-actions"><button class="btn btn-ghost" data-content-action="edit-member" data-id="${m.id}">Edit Member</button><button class="btn btn-primary" data-content-action="add-season" data-id="${m.id}">+ Add Season</button></div><div class="content-season-table"><div class="content-season-row head"><span>Year</span><span>Finish</span><span>Team</span><span>Record</span><span>PF</span><span>PA</span><span></span></div>${seasons.map(s=>`<div class="content-season-row"><span>${s.season_year}</span><span>${Number(s.final_finish)===1?'🏆 ':''}#${s.final_finish}</span><span>${esc(s.team_name)}</span><span>${esc(s.record)}</span><span>${s.points_for??'—'}</span><span>${s.points_against??'—'}</span><span class="content-row-actions"><button class="mini-link" data-content-action="edit-season" data-id="${s.id}" data-member="${m.id}">Edit</button><button class="mini-link danger" data-content-action="delete-season" data-id="${s.id}">Delete</button></span></div>`).join('')||'<div class="staff-empty content-empty-row">No seasons yet.</div>'}</div></article>`}).join('')}</div>`}
  function renderChampions(body){body.innerHTML=`<div class="content-toolbar"><div><h3>League History</h3><div class="staff-meta">Champions, runner-ups, scores, and the story behind each title.</div></div><button class="btn btn-primary" data-content-action="add-champion">+ Add Champion</button></div><div class="content-card-list">${cache.champions.map(c=>`<div class="content-list-card"><div class="content-list-year">${c.season_year}</div><div class="content-list-main"><h3>${esc(c.champion)}</h3><div class="content-detail-line">${c.champion_team?esc(c.champion_team):''}${c.runner_up?` · defeated ${esc(c.runner_up)}`:''}${c.championship_score?` · ${esc(c.championship_score)}`:''}</div><p>${esc(c.note||'')}</p></div><div class="content-row-actions"><button class="btn btn-ghost" data-content-action="edit-champion" data-id="${c.id}">Edit</button><button class="btn btn-ghost staff-danger" data-content-action="delete-champion" data-id="${c.id}">Delete</button></div></div>`).join('')||'<div class="staff-empty">No history entries yet.</div>'}</div>`}
  function renderRecords(body){body.innerHTML=`<div class="content-toolbar"><div><h3>Record Book</h3><div class="staff-meta">Keep league records organized by value, holder, and season/week context.</div></div><button class="btn btn-primary" data-content-action="add-record">+ Add Record</button></div><div class="content-record-grid">${cache.records.map(r=>`<div class="content-record-card"><div class="label">${esc(r.label)}</div><div class="val">${esc(r.value)}</div><div class="content-detail-line">${esc(r.holder||r.detail||'')}</div><div class="staff-meta">${esc(r.season_context||'')}</div><div class="content-row-actions"><button class="btn btn-ghost" data-content-action="edit-record" data-id="${r.id}">Edit</button><button class="btn btn-ghost staff-danger" data-content-action="delete-record" data-id="${r.id}">Delete</button></div></div>`).join('')||'<div class="staff-empty">No records yet.</div>'}</div>`}
  function renderShame(body){body.innerHTML=`<div class="content-toolbar"><div><h3>Wall of Shame</h3><div class="staff-meta">Keep every last-place season and punishment instead of overwriting the previous one.</div></div><button class="btn btn-primary" data-content-action="add-shame">+ Add Entry</button></div><div class="content-card-list">${cache.shame.map(s=>`<div class="content-list-card ${s.is_active?'active-shame':''}"><div class="content-list-year">${s.season_year||'—'}</div><div class="content-list-main"><h3>${esc(s.icon||'💩')} ${esc(s.member_team||s.title)}</h3><div class="content-detail-line">${esc(s.punishment||s.note||'')}</div><p>${esc(s.note||'')}</p></div><div class="content-row-actions"><button class="btn btn-ghost" data-content-action="edit-shame" data-id="${s.id}">Edit</button>${s.is_active?'':'<button class="btn btn-ghost" data-content-action="activate-shame" data-id="'+s.id+'">Show on History</button>'}<button class="btn btn-ghost staff-danger" data-content-action="delete-shame" data-id="${s.id}">Delete</button></div></div>`).join('')||'<div class="staff-empty">No Wall of Shame entries yet.</div>'}</div>`}

  function memberForm(m={}){openModal(m.id?'Edit Member':'Add Member','Basic member information',`${field('Member #','member_number',m.member_number||'','text','required maxlength="4"')}${field('Name','name',m.name||'','text','required')}${field('Role label','role_label',m.role_label||'League Member')}${field('Sort order','sort_order',m.sort_order||cache.members.length+1,'number','min="1"')}${actions()}`,async fd=>{const row={member_number:String(fd.get('member_number')).trim(),name:String(fd.get('name')).trim(),role_label:String(fd.get('role_label')).trim()||'League Member',sort_order:Number(fd.get('sort_order'))||99};const q=m.id?supabase.from('league_members').update(row).eq('id',m.id):supabase.from('league_members').insert(row);const {error}=await q;if(error)throw error})}
  function seasonForm(memberId,s={}){const member=cache.members.find(x=>x.id===memberId);openModal(s.id?'Edit Season':'Add Season',member?.name||'Member',`${field('Season year','season_year',s.season_year||new Date().getFullYear(),'number','required min="2016" max="2100"')}${field('Final finish','final_finish',s.final_finish||'','number','required min="1" max="99"')}${field('Team name','team_name',s.team_name||'','text','required')}${field('Record (W-L or W-L-T)','record',s.record||'','text','required placeholder="8-6 or 8-5-1"')}${field('Points For','points_for',s.points_for??'','number','step="0.01"')}${field('Points Against','points_against',s.points_against??'','number','step="0.01"')}${actions()}`,async fd=>{const record=String(fd.get('record')).trim();if(!/^\d+-\d+(?:-\d+)?$/.test(record))throw new Error('Record must look like 8-6 or 8-5-1.');const row={member_id:memberId,season_year:Number(fd.get('season_year')),final_finish:Number(fd.get('final_finish')),team_name:String(fd.get('team_name')).trim(),record,points_for:fd.get('points_for')===''?null:Number(fd.get('points_for')),points_against:fd.get('points_against')===''?null:Number(fd.get('points_against'))};const q=s.id?supabase.from('member_seasons').update(row).eq('id',s.id):supabase.from('member_seasons').insert(row);const {error}=await q;if(error)throw error})}
  function championForm(c={}){openModal(c.id?'Edit Championship':'Add Championship','League history entry',`${field('Season year','season_year',c.season_year||'','number','required min="2016"')}${field('Champion / owner','champion',c.champion||'','text','required')}${field('Champion team','champion_team',c.champion_team||'')}${field('Runner-up','runner_up',c.runner_up||'')}${field('Championship score','championship_score',c.championship_score||'','text','placeholder="129.64-107.88"')}${textarea('Story / note','note',c.note||'','maxlength="1200"')}${actions()}`,async fd=>{const row={season_year:Number(fd.get('season_year')),champion:String(fd.get('champion')).trim(),champion_team:String(fd.get('champion_team')).trim(),runner_up:String(fd.get('runner_up')).trim(),championship_score:String(fd.get('championship_score')).trim(),note:String(fd.get('note')).trim()};const q=c.id?supabase.from('league_champions').update(row).eq('id',c.id):supabase.from('league_champions').insert(row);const {error}=await q;if(error)throw error})}
  function recordForm(r={}){openModal(r.id?'Edit Record':'Add Record','Record Book entry',`${field('Record category','label',r.label||'','text','required')}${field('Record value','value',r.value||'','text','required')}${field('Holder / team','holder',r.holder||r.detail||'')}${field('Season / week context','season_context',r.season_context||'','text','placeholder="Week 8, 2022"')}${field('Display order','sort_order',r.sort_order||cache.records.length+1,'number','min="1"')}${textarea('Extra detail','detail',r.detail||'')}${actions()}`,async fd=>{const holder=String(fd.get('holder')).trim(),context=String(fd.get('season_context')).trim(),detail=String(fd.get('detail')).trim();const row={label:String(fd.get('label')).trim(),value:String(fd.get('value')).trim(),holder,season_context:context,detail:detail||[holder,context].filter(Boolean).join(' · '),sort_order:Number(fd.get('sort_order'))||99};const q=r.id?supabase.from('league_records').update(row).eq('id',r.id):supabase.from('league_records').insert(row);const {error}=await q;if(error)throw error})}
  function shameForm(s={}){openModal(s.id?'Edit Wall of Shame':'Add Wall of Shame Entry','Last-place history and punishment',`${field('Season year','season_year',s.season_year||'','number','required min="2016"')}${field('Member / team','member_team',s.member_team||s.title||'','text','required')}${field('Punishment','punishment',s.punishment||s.note||'','text')}${field('Icon / emoji','icon',s.icon||'💩')}${textarea('Description / story','note',s.note||'')}${actions()}`,async fd=>{const member=String(fd.get('member_team')).trim(),punishment=String(fd.get('punishment')).trim(),note=String(fd.get('note')).trim();if(!s.id)await supabase.from('wall_of_shame').update({is_active:false}).eq('is_active',true);const row={season_year:Number(fd.get('season_year')),member_team:member,punishment,title:`${member} — Last Place, ${fd.get('season_year')}`,note:note||punishment,icon:String(fd.get('icon')).trim()||'💩',is_active:s.id?s.is_active:true};const q=s.id?supabase.from('wall_of_shame').update(row).eq('id',s.id):supabase.from('wall_of_shame').insert(row);const {error}=await q;if(error)throw error})}

  async function handleAction(e){const tab=e.target.closest('[data-content-tab]');if(tab){activeTab=tab.dataset.contentTab;renderManager();return}const b=e.target.closest('[data-content-action]');if(!b)return;const a=b.dataset.contentAction,id=b.dataset.id;
    if(a==='add-member')return memberForm();if(a==='edit-member')return memberForm(cache.members.find(x=>x.id===id));if(a==='add-season')return seasonForm(id);if(a==='edit-season'){for(const m of cache.members){const s=(m.member_seasons||[]).find(x=>x.id===id);if(s)return seasonForm(m.id,s)}}
    if(a==='add-champion')return championForm();if(a==='edit-champion')return championForm(cache.champions.find(x=>x.id===id));if(a==='add-record')return recordForm();if(a==='edit-record')return recordForm(cache.records.find(x=>x.id===id));if(a==='add-shame')return shameForm();if(a==='edit-shame')return shameForm(cache.shame.find(x=>x.id===id));
    const deletes={ 'delete-season':['member_seasons','Delete this season?'], 'delete-champion':['league_champions','Delete this championship entry?'], 'delete-record':['league_records','Delete this record?'], 'delete-shame':['wall_of_shame','Delete this Wall of Shame entry?'] };
    if(deletes[a]){if(!confirm(deletes[a][1]))return;const {error}=await supabase.from(deletes[a][0]).delete().eq('id',id);if(error)return toast(error.message,'error');await refreshAll();return toast('Deleted ✓')}
    if(a==='delete-member'){if(!confirm('Delete this member and ALL of their seasons? This cannot be undone.'))return;const {error}=await supabase.from('league_members').delete().eq('id',id);if(error)return toast(error.message,'error');await refreshAll();return toast('Member deleted ✓')}
    if(a==='activate-shame'){await supabase.from('wall_of_shame').update({is_active:false}).eq('is_active',true);const {error}=await supabase.from('wall_of_shame').update({is_active:true}).eq('id',id);if(error)return toast(error.message,'error');await refreshAll();toast('History display updated ✓')}
  }

  async function refreshAll(){await loadData();renderManager();await window.refreshLeagueContent?.()}
  async function inject(){if(currentProfile?.role!=='site_admin')return;const staff=document.getElementById('staffContent');if(!staff||document.getElementById('leagueContentPanel'))return;const panel=document.createElement('div');panel.className='panel staff-panel staff-panel-wide';panel.id='leagueContentPanel';panel.innerHTML=`<div class="staff-subhead content-manager-head"><div><h3>League Content Manager</h3><div class="staff-meta">Manage the league like an app — no HTML, JavaScript, or SQL for normal updates.</div></div><button class="btn btn-ghost" id="importSiteDataBtn">Import Current Site Data</button></div><div class="staff-role-note"><strong>Season workflow:</strong> choose a member → Add Season → enter the new year's finish, record, PF and PA. Career record, win %, championships and average finish are calculated automatically.</div><div id="leagueContentManager"><div class="staff-empty">Loading league data…</div></div>`;staff.appendChild(panel);panel.addEventListener('click',handleAction);document.getElementById('importSiteDataBtn').addEventListener('click',e=>importCurrentSiteData(e.currentTarget));try{await loadData();renderManager()}catch(err){document.getElementById('leagueContentManager').innerHTML=`<div class="staff-empty">${esc(err.message)}<br><br>Run <span class="mono">supabase/league_content_manager_upgrade.sql</span> in Supabase if you have not yet applied the Content Manager upgrade.</div>`}}

  window.addEventListener('gate-auth-changed',e=>{currentProfile=e.detail.profile;if(currentProfile?.role==='site_admin')setTimeout(inject,0)});
})();
