(function(){
  const shell=document.querySelector('#history .history-shell');
  if(!shell||shell.querySelector('[data-history-tab="players"]'))return;
  const subnav=shell.querySelector('.history-subnav'),panels=shell.querySelector('.history-tab-panels'),recordBtn=subnav?.querySelector('[data-history-tab="records"]');
  if(!subnav||!panels)return;
  const btn=document.createElement('button');btn.type='button';btn.dataset.historyTab='players';btn.textContent='🏈 Players';
  if(recordBtn)subnav.insertBefore(btn,recordBtn);else subnav.appendChild(btn);
  const panel=document.createElement('section');panel.className='history-tab-panel';panel.dataset.historyPanel='players';panel.innerHTML='<div class="panel history-content-panel player-archive-panel"><div class="history-loading">Open Players to load the archive.</div></div>';
  const recordPanel=panels.querySelector('[data-history-panel="records"]');if(recordPanel)panels.insertBefore(panel,recordPanel);else panels.appendChild(panel);
  const {escapeHtml:esc}=window.gateShared;
  const num=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:2});
  const people={'kyle fowler':'Kyle Fowler','ronnie coiro':'Ronnie Coiro','german joshua haro':'German Haro','german haro':'German Haro','tommy speer':'Thomas Speer'};
  const person=v=>people[String(v??'').trim().toLowerCase()]||String(v??'');
  let loaded=false,indexData=null,mode='career',activeYear=null,yearData=null;
  function activate(){shell.querySelectorAll('[data-history-tab]').forEach(x=>x.classList.toggle('active',x===btn));shell.querySelectorAll('[data-history-panel]').forEach(x=>x.classList.toggle('active',x===panel));ensureLoaded()}
  btn.addEventListener('click',activate);
  async function ensureLoaded(){if(loaded)return;loaded=true;panel.innerHTML='<div class="panel history-content-panel player-archive-panel"><div class="history-loading">Loading player archive…</div></div>';try{const r=await fetch('data/players/index.json',{cache:'no-store'});if(!r.ok)throw new Error(`players index returned HTTP ${r.status}`);indexData=await r.json();activeYear=indexData.years?.[0];build();await loadYear(activeYear)}catch(error){console.error('Unable to load player archive:',error);panel.innerHTML='<div class="panel history-content-panel"><div class="history-loading">Player archive could not be loaded.</div></div>'}}
  function build(){const records=indexData.records||{},high=records.highestWeek||[],season=records.highestSeason||[],career=records.careerPoints||[];panel.innerHTML=`<div class="panel history-content-panel player-archive-panel"><div class="history-section-head"><div><span>PLAYER ARCHIVE</span><h3>Player History</h3></div><small>${Number(indexData.playerCount||0).toLocaleString()} players in archive · leaderboards 2019–2025</small></div><div class="player-record-grid"><article><span>Highest Player Week</span><strong>${num(high[0])} — ${esc(high[1])}</strong><small>${esc(high[2])} · ${high[3]} W${high[4]} · ${esc(person(high[6]))}</small></article><article><span>Highest Season Total</span><strong>${num(season[0])} — ${esc(season[1])}</strong><small>${esc(season[2])} · ${season[3]} · ${esc(person(season[7]))}</small></article><article><span>Archive Career Points</span><strong>${num(career[0])} — ${esc(career[1])}</strong><small>${esc(career[2])} · ${career[3]} seasons · best ${num(career[6])}</small></article></div><div class="player-mode-nav"><button type="button" class="active" data-player-mode="career">Career Leaders</button><button type="button" data-player-mode="season">Season Leaders</button></div><div class="player-year-nav is-hidden">${(indexData.years||[]).map((y,i)=>`<button type="button" class="${i===0?'active':''}" data-player-year="${y}">${y}</button>`).join('')}</div><div class="player-controls"><label>Position<select class="player-pos"><option value="">All positions</option>${['QB','RB','WR','TE','K','D/ST'].map(p=>`<option>${p}</option>`).join('')}</select></label><label>Search<input class="player-search" type="search" placeholder="Search player"></label></div><div class="player-table-wrap"><table class="player-table"><thead></thead><tbody></tbody></table><div class="player-empty" hidden>No players match that filter.</div></div></div>`;
    panel.querySelectorAll('[data-player-mode]').forEach(x=>x.addEventListener('click',()=>setMode(x.dataset.playerMode)));
    panel.querySelectorAll('[data-player-year]').forEach(x=>x.addEventListener('click',()=>loadYear(Number(x.dataset.playerYear))));
    panel.querySelector('.player-pos').addEventListener('change',draw);panel.querySelector('.player-search').addEventListener('input',draw);draw();
  }
  function setMode(next){mode=next;panel.querySelectorAll('[data-player-mode]').forEach(x=>x.classList.toggle('active',x.dataset.playerMode===mode));panel.querySelector('.player-year-nav').classList.toggle('is-hidden',mode!=='season');draw()}
  async function loadYear(year){activeYear=Number(year);panel.querySelectorAll('[data-player-year]').forEach(x=>x.classList.toggle('active',Number(x.dataset.playerYear)===activeYear));try{const r=await fetch(`data/players/${activeYear}.json`,{cache:'no-store'});if(!r.ok)throw new Error(`players/${activeYear}.json returned HTTP ${r.status}`);yearData=await r.json();if(mode==='season')draw()}catch(error){console.error('Unable to load player season:',error)}}
  function draw(){const tbody=panel.querySelector('tbody'),thead=panel.querySelector('thead'),empty=panel.querySelector('.player-empty');if(!tbody||!thead)return;const pos=panel.querySelector('.player-pos')?.value||'',q=(panel.querySelector('.player-search')?.value||'').trim().toLowerCase();if(mode==='career'){thead.innerHTML='<tr><th>Player</th><th>Pos</th><th>Seasons</th><th>Points</th><th>Weeks</th><th>Starts</th><th>Best Week</th></tr>';const rows=(indexData?.careers||[]).filter(p=>(!pos||p[2]===pos)&&(!q||p[1].toLowerCase().includes(q)));tbody.innerHTML=rows.map(p=>`<tr><td class="player-name"><strong>${esc(p[1])}</strong></td><td><span class="player-pos-tag">${esc(p[2])}</span></td><td>${p[3]}</td><td class="player-points">${num(p[4])}</td><td>${p[5]}</td><td>${p[6]}</td><td><strong>${num(p[7])}</strong><small>${p[8]} W${p[9]}</small></td></tr>`).join('');empty.hidden=rows.length>0}else{thead.innerHTML='<tr><th>Rank</th><th>Player</th><th>Pos</th><th>Points</th><th>Weeks</th><th>Starts</th><th>Best</th><th>Primary Fantasy Team</th></tr>';const rows=(yearData?.players||[]).filter(p=>(!pos||p[2]===pos)&&(!q||`${p[1]} ${p[8]} ${person(p[9])}`.toLowerCase().includes(q)));tbody.innerHTML=rows.map((p,i)=>`<tr><td class="player-rank">#${i+1}</td><td class="player-name"><strong>${esc(p[1])}</strong></td><td><span class="player-pos-tag">${esc(p[2])}</span></td><td class="player-points">${num(p[3])}</td><td>${p[4]}</td><td>${p[5]}</td><td><strong>${num(p[6])}</strong><small>W${p[7]}</small></td><td><strong>${esc(p[8])}</strong><small>${esc(person(p[9]))}</small></td></tr>`).join('');empty.hidden=rows.length>0}}
})();
